server:
  port: 8002

spring:
  application:
    name: msa-payment

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka