server:
  port: 8002

spring:
  application:
    name: msa-payment

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka